### ISSUE TITLE
Optische Gestaltung des Backends für Admins, Redakteure und Autoren

### ISSUE THREAD

**Issue by Erik-2007** [FAU-Brand/Lastenheft#34]
Zum Beispiel
- Strukturierte Möglichkeit Seiten anzeigen zu lassen (Seitenbaum)
- Unterschiedliche Custom Post Types, je nach Beitragsart
- Auf Seiten und Beiträgen Auswahl an Design-Vorlagen gekoppelt an Berechtigungen und Seitentypen
- **Mediathek:** Möglichkeit Medien (Bilder, Videos, Dokumente) übersichtlich anzeigen zu lassen
- **Mediathek:** Möglichkeit nach unbenutzten Bildern, Dokumenten, Videos usw. zu filtern 
- gerne Vorschläge machen

**Comment by lukasniebler** [comment]
Wichtige vielleicht:

Die Rollenverwaltung läuft derzeit über unser RRZE Workflow-Plugin. Core-Funktionen und erweiternde Core-Funktionen (Durchsuchen d. Seitenbaums, Löschen von unbenutzten Dateien etc. sind in unserem Settings-Plugin eigentlich besser angesiedelt (bzw. waren da auch teilweise schonmal vorhanden)). Das ist weniger Sache eines Themes.

Bei der Gestaltung des Backends im Sinne von Metaboxen, Patterns und Co. liegt das schon auf Seiten der Agentur. Aber die Beispiele ganz oben sind alle eigentlich Sonderwünsche die auf Plugin-Seite liegen müssten:

**Strukturierte Möglichkeit Seiten anzeigen zu lassen (Seitenbaum)**
Funktion gab es bereits im Settings-Plugin wurde aber deaktiviert aus technischen Gründen

**Unterschiedliche Custom Post Types (CPT), je nach Beitragsart**
CPT werden meistens aus Plugins geliefert und sind dort eigentlich auch besser aufgehoben, damit in Zukunft bei einem Theme-Wechsel keine Daten verloren gehen.

**Auf Seiten und Beiträgen Auswahl an Design-Vorlagen gekoppelt an Berechtigungen und Seitentypen**
Das sollten wir bei den technischen Anforderungen noch ergänzen

**Mediathek: Möglichkeit Medien (Bilder, Videos, Dokumente) übersichtlich anzeigen zu lassen**
Die Mediathek ist Bestandteil von WordPress Core und wird nicht durch das Theme beeinflusst.

**Mediathek: Möglichkeit nach unbenutzten Bildern, Dokumenten, Videos usw. zu filtern**
Das wär auch ein Sonderwunsch für das Settings-Plugin

@xwolfde – Willst du nochmal drüber schauen.

**Comment by xwolfde** [comment]
Es ist wichtig zu verstehen, dass wir in einem CMS Kontext arbeiten. Das bedeutet, dass Inhalt und Optik stets getrennt zu betrachten sind.

Ein Theme macht im Wesentlichen "nur" die Optik. Also das Frontend, was nach aussen zu sehen ist. 
Die Logik und die Contenterstellung ist hingegen Domäne des CMS-Coresystems (WordPress) und von Plugins.


Platt gesagt: Das Theme ist allein für die Optische Darstellung von Content zuständig. Wie dieser Content erstellt oder verwaltet und von welchen Drittdatenquellen er geholt wurde, ist für das Theme irrelevant.


Die optische Gestaltung des Backend wird von dem CMS WordPress vorgegeben.
Es wäre zwar denkbar, hier eigene Anpassungender Backend-Optik vorzunehmen, die dann auch vom Theme kämen, dies wäre jedoch nicht ratsam, sondern auch im Sinne des langjährigen Supports ziemlich tödlich: Das native WordPress Backend ist allseits bekannt und wird in Schulungen gezeigt und gelehrt. Es ist optimiert und unterliegt stetigen Verbesserungen durch internationel Teams. Ein eigenes Backend zu gestalten wäre sehr aufwendig und würde User, die WordPress kennen und Kurse besucht haben, unnötig verwirren.

Hinzu kommt, dass es im kommenden Jahr viele Neuerungen und Modernisierungen des Backends geben wird. 
Keine seriöse Agentur wird daher im aktuellen Stand der Entwicklung des WP Core Backends, wo viele Änderungen und ENtwicklungen noch nicht klar und noch nicht etabliert sind, Hand an das Backend legen und kundenindividuelle Anpassungen vornehmen.

**Comment by Erik-2007** [comment]
Vielen Dank für die Inputs :). 
Ich bin mir der Trennung von Inhalt und Optik bewusst. Einen Webseiten-Relaunch verstehe ich allerdings umfassender und dachte, dass man beispielsweise auch die Nutzererfahrung für die Autoren, Redakteure und Admins in diesem Zuge verbessern kann. 
Und wenn ich das richtig verstehe, kann man das auch, nur sind es eher Issues für das Rechenzentrum und nicht für eine Agentur. Wobei eine Agentur evtl. ja schon interessanten Input zu solchen Themen liefern könnte.  

So langsam bekomme ich ein Gefühl, dafür, was ein Issue für euch ist und was für die Agentur bestimmt wäre. Ich sammle gerade schon fleißig und werde dann in Absprache mit der Webredaktion im RRZE GitHub entsprechende Anfragen stellen. 

Dieses Issue werde ich dann closen.

**Comment by xwolfde** [comment]
Hinsichtlich redaktionelle Kontrolle sollten wir uns ggf. auch mal austauschen bzgl. der gewünschten und der tatsächlichen Praxis. Aber vielleicht hat Cathrin dir dazu ja schon Einblicke gegeben.
In Kurz: Redaktionelle Kontrolle und Workflows dazu sind möglich und vorhanden. Können aber nur dort gelebt werden, wo es ein Team an Webredakteuren gibt.  Bei allen Einrichtungen bei der nur eine Handvoll an Beschäftigten Websites machen, wurden die entsprechenden Tools durch die Webmaster wieder abgeschaltet oder dadurch workarounded, indem alle User zu Amdins gemacht wurden => Diese Verfahren sind nur auf dem Theoriepapier gut; im Alltag eines Lehrstuhls aber nicht praktikabel.
Aktuell gibt es nur 3 große Websites, die redaktionelle Kontrolle so nutzen, wie sie gedacht ist: FAU-Hauptseite mit Webredaktion, RRZE mit unserer Webredaktion und MeinStudium.

**Comment by Erik-2007** [comment]
Ja, sehr gerne! Habe das so zwar schon mitbekommen, bin aber über einen Austausch zu diesem Thema definitiv interessiert.
