### ISSUE TITLE
Umfassendes Berechtigungsmanagement

### ISSUE THREAD

**Issue by Erik-2007** [FAU-Brand/Lastenheft#35]
Vorschlag für ein ausgeklügeltes Berechtigungsmanagement, das mehr Anpassungsmöglichkeiten, als die in WordPress bereits vorhandenen Rollen (Admin, Redakteur, Autor) bietet. 
z.B. Möglichkeit bieten, den jeweiligen Rollen einzelne Zusatzrechte zuzuweisen oder weitere Rollen festlegen. 

Ziel ist es hier, eine einfache Bedienung für die verschiedenen Benutzerebenen im CMS zu gewährleisten. Welche Musterseiten, Blöcke, Backend-Funktionen etc. stehen den verschiedenen Rollen zur Verfügung?

### Mögliche Ergebnistypen:
- Beschreibung des Konzepts in Text oder Strukturvisualisierung (Textdokument, Präsentation)
- beispielhafte Skizze verschiedener Funktionen und Zustände zur Verdeutlichung des Konzepts in einem geeigneten Visualisierungstool (z.B. Figma)

**Comment by lukasniebler** [comment]
Das Workflow-Plugin des RRZE ist für die Berechtigungsverwaltung zuständig. Die Überarbeitung der Benutzerrollen kann während dem FAU Rebrush bereits bedacht und umgesetzt werden, deshalb schließe ich den Fall hier und nehme es für die Einführung des Gutenberg-Editors mit auf.
