### ISSUE TITLE
Bitte prüfen, ob wir diesen Punkt brauchen --- Suchmaschinenoptimierung

### ISSUE THREAD

**Issue by Erik-2007** [FAU-Brand/Lastenheft#37]
Laut Leistungsbeschreibung: 

**4.2	Suchmaschinenoptimierung**
Eine wichtige Anforderung ist die Entwicklung einer umfassenden SEO-Strategie für die Webseiten der FAU. Die Strategie soll alle relevanten Aspekte der Suchmaschinenoptimierung abdecken und dazu beitragen, die Sichtbarkeit der Webseiten in Suchmaschinen zu maximieren. Dies beinhaltet:
**4.2.1 Leitfaden**
Das digitale Umfeld der FAU ist komplex und dezentral, daher ist zu beachten, dass nicht alle Parameter und Keywords für z.B. Lehrstühle zentral vorgegeben werden können. Daher muss die Strategie auch ein Konzept bzw. einen Leitfaden für die eigenständige SEO-Optimierung von Unterseiten mit entsprechenden Do‘s and Dont‘s beinhalten.
**4.2.2 Keyword-Analyse**
Eine gründliche Analyse der relevanten Keywords im Kontext der Universität, um eine zielgerichtete Optimierung der Inhalte zu ermöglichen.
**4.2.3 On-Page-Optimierung**
Die Erarbeitung von klaren Richtlinien zur Optimierung von Meta-Tags, Überschriften, Bildern und anderen On-Page-Faktoren zur Verbesserung der Website-Relevanz.
**4.2.4 Technische SEO**
Identifikation und Lösung technischer Probleme, die die Indexierung durch Suchmaschinen beeinträchtigen könnten, sowie Empfehlungen zur Verbesserung der Website-Geschwindigkeit und Benutzerfreundlichkeit.
**4.2.5 Backlink-Strategie**
Entwicklung von Strategien zur natürlichen und qualitativ hochwertigen Backlink-Gewinnung, um die Autorität der Website zu steigern.

_Es wird darauf hingewiesen, dass die dauerhafte Begleitung und Umsetzung der SEO-Strategie nicht Bestandteil dieser Ausschreibung ist. Das Hauptziel liegt in der Konzeption und Entwicklung einer umfassenden SEO-Strategie, die anschließend vom internen Team der FAU implementiert werden kann._ 

### Minimalanforderung
- Konzeptidee, wie ein teilweise dezentralisierter Multi-Site-SEO-Prozess mit verschiedenen Interessengruppen gestaltet werden kann. (Eventuell notwendige Regeln und Richtlinien können im Projektteam diskutiert und festgelegt werden).

**Comment by Erik-2007** [comment]
SEO im Backend wird derzeit mit dem Plugin **SEO Framework** umgesetzt. Das soll wahrscheinlich beibehalten werden.

**Comment by Erik-2007** [comment]
Brauchen wir diesen Punkt eigentlich für das Lastenheft, bzw. vielleicht nur Minimalanforderung aufführen?

**Comment by lukasniebler** [comment]
Es gibt bereits eine SEO-Anleitung, die unsere Website-Nutzer klare Leitsätze und Richtlinien an die Hand gibt. Die [SEO-Anleitung](https://www.wordpress.rrze.fau.de/tutorials/seo-tutorial/seo-grundlagen-inhalte-gestalten/) wurde nie groß beworben, wäre aber geeignet, um den Bereich SEO gut abzudecken.

Deshalb macht es in meinen Augen wenig Sinn noch einmal ein SEO-Konzept in Auftrag zu geben, v.a. da der Bereich des technischen SEO bereits durch The SEO Framework abgedeckt wird.

Auch die Keyword-Analyse macht keinen Sinn, da eine externe Agentur nicht für alle 800 Websites keywords identifizieren kann. SEO ist ein Seiten-für-Seiten-Thema

Als Websupport stellen wir für SEO notwendigen Leitsätze und Richtlinien gerne bereit, die 
a) von den Nutzern einfach umgesetzt werden können
b) die auf Lange Sicht die Sichtbarkeit der Websites erhöhen

Vgl. https://www.wordpress.rrze.fau.de/tutorials/seo-tutorial/seo-grundlagen-inhalte-gestalten/
-

Dahingehend seh ich auch SEO als zukünftige Aufgabe im Projektverlauf als Aufgabe bei der Schulung der User
