### ISSUE TITLE
Kontextbezogene und (teil-)automatisierte Einbindung von "Weitere Beiträge zum Thema"

### ISSUE THREAD

**Issue by Erik-2007** [FAU-Brand/Lastenheft#45]
Unter einem Beitrag, auf der Startseite oder auch auf Zwischenmenüseiten (u.a.) sollte die Möglichkeit bestehen, Beiträge zum jeweiligen Thema anzuzeigen, beispielsweise indem man ihm einen bestimmten Tag o.ä. zuweist. Dabei sollte der Pflegeaufwand für die Admins möglichst gering gehalten werden. Es braucht also ein Konzept, wie die Meldungen automatisch an der gewünschten Stelle erscheinen und auch wieder verschwinden, sobald neue eingefügt werden.

**Comment by lukasniebler** [comment]
Enthalten in Abwärtskompatibilität in der eVergabe
